---
name: "DoesTheDogDie"
guid: "c84eb73f-949b-45c4-aa0a-294b94030aed"
version: "0.0.0.3"
targetAbi: "10.11.6"
framework: "net9.0"
overview: "Integrates the DoesTheDogDie API into Jellyfin, allowing users to see content warnings for media items based on the presence of certain triggers."
description: >
  ntegrates the DoesTheDogDie API into Jellyfin, allowing users to see content warnings for media items based on the presence of certain triggers.
category: "General"
owner: "Luca Nixdorf"
artifacts:
  - "Jellyfin.Plugin.DDD.dll"
changelog: >
  changelog
